package com.duriancare.farm.domain;

public enum FarmAuthorizationAuditAction {
    INVITATION_CREATED,
    INVITATION_ACCEPTED,
    INVITATION_REJECTED,
    INVITATION_CANCELLED,
    INVITATION_EXPIRED,
    AUTHORIZATION_CREATED,
    AUTHORIZATION_UPDATED,
    AUTHORIZATION_REVOKED,
    AUTHORIZATION_EXPIRED
}
