package com.duriancare.farm.domain;

public enum FarmPermissionType {
    VIEW_FARM,
    VIEW_CULTIVATION_AREA,
    VIEW_SENSOR_DATA,
    VIEW_ALERTS,
    VIEW_DEVICES,
    VIEW_CARE_SCHEDULE,
    CREATE_CARE_SCHEDULE,
    UPDATE_CARE_SCHEDULE,
    DELETE_CARE_SCHEDULE,
    REQUEST_IRRIGATION_CONTROL,
    CONTROL_IRRIGATION,
    CHAT_WITH_OWNER,
    READ_IOT,
    READ_DISEASE,
    CREATE_PROTOCOL,
    UPDATE_PROTOCOL,
    CONFIGURE_DEVICE
}
