package com.duriancare.cultivation.domain;

public enum ActivityType {
    IRRIGATION,
    FERTILIZATION,
    FERTIGATION,
    BIOLOGICAL_TREATMENT,
    CHEMICAL_TREATMENT,
    PEST_MONITORING,
    DISEASE_MONITORING,
    PRUNING,
    ORCHARD_SANITATION,
    WEED_CONTROL,
    SOIL_IMPROVEMENT,
    POLLINATION,
    FRUIT_BAGGING,
    SOIL_SAMPLING,
    WATER_SAMPLING,
    LEAF_SAMPLING,
    FRUIT_SAMPLING,
    HARVEST,
    OTHER
}
