package com.duriancare.cultivation.domain;

public enum AuditAction {
    CULTIVATION_PLAN_CREATED,
    CULTIVATION_ACTIVITY_CREATED,
    CULTIVATION_ACTIVITY_UPDATED,
    CULTIVATION_ACTIVITY_APPROVED,
    CULTIVATION_ACTIVITY_REJECTED,
    CULTIVATION_ACTIVITY_COMPLETED,
    CULTIVATION_ACTIVITY_SKIPPED,
    CULTIVATION_ACTIVITY_CANCELLED,
    AGRICULTURAL_INPUT_CREATED,
    RESIDUE_STANDARD_CREATED,
    LAB_SAMPLE_CREATED,
    LAB_RESULT_RECORDED,
    HARVEST_BATCH_CREATED,
    SAFE_HARVEST_DATE_OVERRIDDEN,
    COMPLIANCE_ASSESSED,
    EXPORT_RELEASE_CREATED,
    EXPORT_RELEASE_SUBMITTED,
    EXPORT_RELEASE_APPROVED,
    EXPORT_RELEASE_RELEASED,
    EXPORT_RELEASE_RECALLED
}
