package com.duriancare.cultivation.domain;

public enum BlockingReason {
    PROHIBITED_INPUT_USED,
    ACTIVE_INGREDIENT_NOT_ALLOWED_FOR_MARKET,
    PRE_HARVEST_INTERVAL_NOT_MET,
    MAXIMUM_DOSE_EXCEEDED,
    MISSING_EXECUTION_RECORD,
    MISSING_INPUT_INFORMATION,
    MISSING_ACTIVE_INGREDIENT,
    LAB_TEST_REQUIRED,
    LAB_RESULT_FAILED,
    LAB_RESULT_PENDING,
    NO_APPLICABLE_MRL,
    UNAPPROVED_CHEMICAL_APPLICATION
}
