package com.duriancare.cultivation.domain;

public enum ComplianceWarning {
    BIOLOGICAL_ALTERNATIVE_NOT_RECORDED,
    REPEATED_ACTIVE_INGREDIENT_USE,
    HIGH_CHEMICAL_APPLICATION_FREQUENCY,
    MISSING_WEATHER_INFORMATION,
    MISSING_BATCH_NUMBER,
    NEAR_PRE_HARVEST_INTERVAL,
    NEIGHBORING_PLOT_DRIFT_RISK
}
