const now = new Date();

const farmDb = db.getSiblingDB("duriancare_farm");
const cultivationDb = db.getSiblingDB("duriancare_cultivation");

const farmId = "farm-minh-phat-2026";
const zoneAId = "plot-khu-a-truong-thanh";
const zoneBId = "plot-khu-b-ra-hoa";
const seasonId = "season-minh-phat-2026";
const planId = "plan-minh-phat-vu-2026";
const ownerId = "seed-owner-farmer";
const expertId = "seed-expert-approval";

farmDb.farms.updateOne(
  { _id: farmId },
  {
    $set: {
      ownerUserId: ownerId,
      name: "Trang trại Minh Phát",
      address: "Ấp Tân Phong, Cai Lậy",
      province: "Tiền Giang",
      district: "Cai Lậy",
      latitude: NumberDecimal("10.4125"),
      longitude: NumberDecimal("106.1187"),
      areaHectares: NumberDecimal("6.5"),
      status: "ACTIVE",
      zones: [
        {
          id: zoneAId,
          name: "Khu A - Cây trưởng thành",
          code: "A",
          areaSquareMeters: NumberDecimal("28000"),
          boundaryGeoJson: {},
          description: "Khu sầu riêng Dona 9 năm tuổi, đang nuôi trái.",
          status: "ACTIVE",
          createdAt: now,
          updatedAt: now,
        },
        {
          id: zoneBId,
          name: "Khu B - Giai đoạn ra hoa",
          code: "B",
          areaSquareMeters: NumberDecimal("21000"),
          boundaryGeoJson: {},
          description: "Khu Ri6 7 năm tuổi, đang xử lý ra hoa.",
          status: "ACTIVE",
          createdAt: now,
          updatedAt: now,
        },
      ],
      createdAt: now,
      updatedAt: now,
    },
  },
  { upsert: true },
);

cultivationDb.cultivation_plans.updateOne(
  { _id: planId },
  {
    $set: {
      farmId,
      plotId: zoneAId,
      cultivationSeasonId: seasonId,
      templateId: null,
      name: "Kế hoạch chăm sóc vụ mùa 2026",
      startDate: ISODate("2026-07-01T00:00:00Z"),
      expectedHarvestDate: ISODate("2026-08-25T00:00:00Z"),
      targetMarketCodes: ["VN", "EU"],
      status: "ACTIVE",
      createdBy: ownerId,
      createdAt: now,
      updatedAt: now,
    },
  },
  { upsert: true },
);

const activities = [
  {
    _id: "activity-tuoi-nuoc-sang-2026-07-13",
    cultivationPlanId: planId,
    cultivationSeasonId: seasonId,
    farmId,
    plotId: zoneAId,
    treeIds: [],
    activityType: "IRRIGATION",
    title: "Tưới nước buổi sáng",
    description: "Tưới giữ ẩm khu A sau giai đoạn nắng kéo dài.",
    scheduledStartAt: ISODate("2026-07-13T00:00:00Z"),
    scheduledEndAt: ISODate("2026-07-13T01:00:00Z"),
    recurrenceRule: null,
    priority: "HIGH",
    status: "SCHEDULED",
    assignedUserIds: [ownerId],
    approvalRequired: false,
    approvedBy: null,
    approvedAt: null,
    rejectionReason: null,
    createdAt: now,
    updatedAt: now,
  },
  {
    _id: "activity-kiem-tra-sau-benh-2026-07-13",
    cultivationPlanId: planId,
    cultivationSeasonId: seasonId,
    farmId,
    plotId: zoneBId,
    treeIds: [],
    activityType: "PEST_MONITORING",
    title: "Kiểm tra sâu bệnh khu B",
    description: "Quan sát lá non, bông và ghi nhận dấu hiệu rệp sáp.",
    scheduledStartAt: ISODate("2026-07-13T07:30:00Z"),
    scheduledEndAt: ISODate("2026-07-13T08:30:00Z"),
    recurrenceRule: null,
    priority: "MEDIUM",
    status: "SCHEDULED",
    assignedUserIds: [ownerId],
    approvalRequired: false,
    approvedBy: null,
    approvedAt: null,
    rejectionReason: null,
    createdAt: now,
    updatedAt: now,
  },
  {
    _id: "activity-bon-phan-huu-co-2026-07-14",
    cultivationPlanId: planId,
    cultivationSeasonId: seasonId,
    farmId,
    plotId: zoneAId,
    treeIds: [],
    activityType: "FERTILIZATION",
    title: "Bón phân hữu cơ",
    description: "Bón phân hữu cơ vi sinh quanh tán, kết hợp tưới nhẹ.",
    scheduledStartAt: ISODate("2026-07-14T01:00:00Z"),
    scheduledEndAt: ISODate("2026-07-14T03:00:00Z"),
    recurrenceRule: null,
    priority: "MEDIUM",
    status: "IN_PROGRESS",
    assignedUserIds: [ownerId],
    approvalRequired: false,
    approvedBy: null,
    approvedAt: null,
    rejectionReason: null,
    createdAt: now,
    updatedAt: now,
  },
  {
    _id: "activity-phun-sinh-hoc-2026-07-15",
    cultivationPlanId: planId,
    cultivationSeasonId: seasonId,
    farmId,
    plotId: zoneAId,
    treeIds: [],
    activityType: "BIOLOGICAL_TREATMENT",
    title: "Phun chế phẩm sinh học",
    description: "Phun Trichoderma Bio phòng nấm vùng rễ.",
    scheduledStartAt: ISODate("2026-07-15T08:00:00Z"),
    scheduledEndAt: ISODate("2026-07-15T09:30:00Z"),
    recurrenceRule: null,
    priority: "MEDIUM",
    status: "SCHEDULED",
    assignedUserIds: [ownerId],
    approvalRequired: false,
    approvedBy: null,
    approvedAt: null,
    rejectionReason: null,
    createdAt: now,
    updatedAt: now,
  },
  {
    _id: "activity-yeu-cau-phun-hoa-chat-2026-07-16",
    cultivationPlanId: planId,
    cultivationSeasonId: seasonId,
    farmId,
    plotId: zoneBId,
    treeIds: [],
    activityType: "CHEMICAL_TREATMENT",
    title: "Đề nghị xử lý rệp sáp bằng thuốc chọn lọc",
    description: "Chỉ thực hiện nếu chuyên gia phê duyệt sau khi kiểm tra IPM.",
    scheduledStartAt: ISODate("2026-07-16T08:00:00Z"),
    scheduledEndAt: ISODate("2026-07-16T09:00:00Z"),
    recurrenceRule: null,
    priority: "HIGH",
    status: "PENDING_APPROVAL",
    assignedUserIds: [ownerId],
    approvalRequired: true,
    approvedBy: null,
    approvedAt: null,
    rejectionReason: null,
    createdAt: now,
    updatedAt: now,
  },
  {
    _id: "activity-cat-tia-2026-07-10",
    cultivationPlanId: planId,
    cultivationSeasonId: seasonId,
    farmId,
    plotId: zoneAId,
    treeIds: [],
    activityType: "PRUNING",
    title: "Cắt tỉa cành sâu trong tán",
    description: "Tạo thông thoáng tán cây, gom cành ra khỏi vườn.",
    scheduledStartAt: ISODate("2026-07-10T01:00:00Z"),
    scheduledEndAt: ISODate("2026-07-10T03:00:00Z"),
    recurrenceRule: null,
    priority: "LOW",
    status: "COMPLETED",
    assignedUserIds: [ownerId],
    approvalRequired: false,
    approvedBy: null,
    approvedAt: null,
    rejectionReason: null,
    createdAt: now,
    updatedAt: now,
  },
];

activities.forEach((activity) => {
  cultivationDb.cultivation_activities.updateOne(
    { _id: activity._id },
    { $set: activity },
    { upsert: true },
  );
});

const inputs = [
  {
    _id: "input-trichoderma-bio",
    code: "TRICHO-BIO-001",
    productName: "Trichoderma Bio",
    tradeName: "Trichoderma Bio",
    manufacturer: "DurianCare Lab",
    registrationNumber: "BIO-2026-001",
    category: "BIOLOGICAL_CONTROL",
    biologicalLevel: "BIOLOGICAL",
    formulation: "WP",
    unit: "g",
    activeIngredients: [],
    beneficialOrganisms: ["Trichoderma harzianum"],
    recommendedDose: "500 g / 200 lít nước",
    maximumDose: "700 g / 200 lít nước",
    preHarvestIntervalDays: 0,
    reEntryIntervalHours: 4,
    targetPests: ["Nấm vùng rễ"],
    applicableCrops: ["DURIAN"],
    allowedMarketCodes: ["VN", "EU", "CN", "JP"],
    prohibitedMarketCodes: [],
    labelDocumentUrl: null,
    certificateDocumentUrls: [],
    status: "VERIFIED",
    verifiedBy: expertId,
    verifiedAt: now,
    createdAt: now,
    updatedAt: now,
  },
  {
    _id: "input-neem-oil",
    code: "NEEM-OIL-001",
    productName: "Chế phẩm Neem",
    tradeName: "Neem Oil",
    manufacturer: "GreenFarm",
    registrationNumber: "BIO-2026-002",
    category: "BOTANICAL_PRODUCT",
    biologicalLevel: "LOW_RISK",
    formulation: "EC",
    unit: "ml",
    activeIngredients: [{ code: "AZADIRACHTIN", name: "Azadirachtin", concentration: 0.3, concentrationUnit: "%" }],
    beneficialOrganisms: [],
    recommendedDose: "300 ml / 200 lít nước",
    maximumDose: "500 ml / 200 lít nước",
    preHarvestIntervalDays: 3,
    reEntryIntervalHours: 12,
    targetPests: ["Rệp sáp", "Bọ trĩ"],
    applicableCrops: ["DURIAN"],
    allowedMarketCodes: ["VN", "EU"],
    prohibitedMarketCodes: [],
    labelDocumentUrl: null,
    certificateDocumentUrls: [],
    status: "VERIFIED",
    verifiedBy: expertId,
    verifiedAt: now,
    createdAt: now,
    updatedAt: now,
  },
  {
    _id: "input-imidacloprid-selective",
    code: "IMIDA-SELECT-001",
    productName: "Thuốc chọn lọc Imida 100SL",
    tradeName: "Imida 100SL",
    manufacturer: "AgriSafe",
    registrationNumber: "CHEM-2026-018",
    category: "CHEMICAL_PESTICIDE",
    biologicalLevel: "RESTRICTED_CHEMICAL",
    formulation: "SL",
    unit: "ml",
    activeIngredients: [{ code: "IMIDACLOPRID", name: "Imidacloprid", concentration: 100, concentrationUnit: "g/L" }],
    beneficialOrganisms: [],
    recommendedDose: "80 ml / 200 lít nước",
    maximumDose: "120 ml / 200 lít nước",
    preHarvestIntervalDays: 21,
    reEntryIntervalHours: 24,
    targetPests: ["Rệp sáp"],
    applicableCrops: ["DURIAN"],
    allowedMarketCodes: ["VN"],
    prohibitedMarketCodes: ["EU"],
    labelDocumentUrl: null,
    certificateDocumentUrls: [],
    status: "VERIFIED",
    verifiedBy: expertId,
    verifiedAt: now,
    createdAt: now,
    updatedAt: now,
  },
];

inputs.forEach((input) => {
  cultivationDb.agricultural_inputs.updateOne(
    { _id: input._id },
    { $set: input },
    { upsert: true },
  );
});

cultivationDb.residue_standards.updateOne(
  { _id: "mrl-eu-imidacloprid-durian" },
  {
    $set: {
      marketCode: "EU",
      commodityCode: "DURIAN",
      commodityName: "Sầu riêng",
      activeIngredientCode: "IMIDACLOPRID",
      activeIngredientName: "Imidacloprid",
      mrlValue: NumberDecimal("0.01"),
      unit: "mg/kg",
      effectiveFrom: ISODate("2026-01-01T00:00:00Z"),
      effectiveTo: null,
      sourceType: "EU",
      sourceReference: "EU customer specification 2026",
      verified: true,
      active: true,
      createdAt: now,
      updatedAt: now,
    },
  },
  { upsert: true },
);

cultivationDb.harvest_batches.updateOne(
  { _id: "harvest-batch-minh-phat-2026-001" },
  {
    $set: {
      batchCode: "MP-2026-DONA-001",
      cultivationSeasonId: seasonId,
      farmId,
      plotId: zoneAId,
      harvestedAt: ISODate("2026-08-25T01:00:00Z"),
      quantity: NumberDecimal("1250"),
      quantityUnit: "kg",
      expectedDestinationMarket: "VN",
      latestSafeHarvestDate: ISODate("2026-08-20T00:00:00Z"),
      chemicalRiskLevel: "LOW",
      status: "APPROVED",
      createdBy: ownerId,
      createdAt: now,
    },
  },
  { upsert: true },
);

cultivationDb.lab_samples.updateOne(
  { _id: "lab-sample-minh-phat-2026-001" },
  {
    $set: {
      cultivationSeasonId: seasonId,
      harvestBatchId: "harvest-batch-minh-phat-2026-001",
      sampleCode: "LAB-MP-2026-001",
      sampleType: "FRUIT",
      sampledAt: ISODate("2026-08-18T02:00:00Z"),
      sampledBy: ownerId,
      samplingLocation: "Khu A - Cây trưởng thành",
      laboratoryName: "Trung tâm kiểm nghiệm Tiền Giang",
      laboratoryAccreditation: "ISO/IEC 17025",
      status: "COLLECTED",
      attachments: [],
      createdAt: now,
    },
  },
  { upsert: true },
);

print("Seeded DurianCare farm and cultivation calendar data.");
