ALTER TABLE user_profiles
    ADD COLUMN IF NOT EXISTS date_of_birth DATE,
    ADD COLUMN IF NOT EXISTS gender VARCHAR(32),
    ADD COLUMN IF NOT EXISTS province_city VARCHAR(150),
    ADD COLUMN IF NOT EXISTS bio VARCHAR(500);
