server:
  port: ${SERVER_PORT:8081}

spring:
  data:
    mongodb:
      uri: ${MONGODB_URI:mongodb://localhost:27017/duriancare_auth}
      auto-index-creation: true
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:}
