server:
  port: ${SERVER_PORT:18084}

spring:
  data:
    mongodb:
      uri: ${CULTIVATION_MONGODB_URI:${MONGODB_URI:mongodb://localhost:27018/duriancare_cultivation}}
      auto-index-creation: true
